Repository Sticky-Seacher/sticky-searcher-website, pull requests merged in 2025-01, with the labels that each got.

#1 [환경구축] 보일러플레이트 설정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .gitignore
  .husky/pre-commit
  .node-version
  .nvmrc
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/index.css
  src/main.jsx
  src/output.css
  tailwind.config.js
  vite.config.js
Labels: chore

#4 feat: history page UI 제작
  index.html
  src/App.jsx
  src/History/HistoryItem.jsx
  src/History/KeywordGroup.jsx
  src/History/NewKeyword.jsx
  src/History/SearchKeyword.jsx
  src/History/SearchSection.jsx
  src/History/SearchUrl.jsx
  src/Home.jsx
  src/assets/emptyPage_search.png
  src/assets/input-search.png
  src/assets/sticky-seacher-logo.png
  src/shared/DeleteButton.jsx
  src/shared/Initial.jsx
  src/shared/Login.jsx
  src/shared/NewKeywordButton.jsx
Labels: feat, D+1

#8 feat: 사용자 임의 history 분류 기능
  src/History/DragAndDrop.jsx
  src/History/HistoryItem.jsx
  src/History/KeywordGroup.jsx
  src/History/SearchKeyword.jsx
  src/History/SearchSection.jsx
  src/Home.jsx
  src/shared/DeleteButton.jsx
Labels: feat, D-0

#12 feat: history item 기능
  sample.json
  src/History/DragAndDrop.jsx
  src/History/HistoryItem.jsx
  src/History/KeywordGroup.jsx
  src/History/SearchKeyword.jsx
  src/History/SearchSection.jsx
  src/History/SearchUrl.jsx
  src/History/TotalKeywordButton.jsx
  src/shared/DeleteButton.jsx
  src/shared/NewKeywordButton.jsx
Labels: feat, D-0

#14 fix: history item 렌더링 시 keyword 동기화
  package-lock.json
  package.json
  src/History/DragAndDrop.jsx
  src/History/HistoryItem.jsx
  src/History/KeywordGroup.jsx
  src/History/NewKeyword.jsx
  src/History/SearchKeyword.jsx
  src/History/SearchUrl.jsx
Labels: D-0, fix

#16 chore: daisyUI 추가
  package-lock.json
  package.json
  tailwind.config.js
Labels: D-0, chore

#17 feat: history item 내 다수 키워드 토글 처리
  src/History/HistoryItem.jsx
  src/History/TotalKeywordButton.jsx
Labels: feat, D+1

#25 feat: webSite 로그인 기능 구현
  src/App.jsx
  src/shared/Login.jsx
Labels: feat, D+1

#21 feat: firestore연동을 위해 group 스키마 기능 추가
  src/firebase/getHistoryGroups.js
  src/firebase/group.js
Labels: feat, D+1

#20 feat: keyword Group 추가 기능
  src/History/ChangeGroupName.jsx
  src/History/DragAndDrop.jsx
  src/History/KeywordGroup.jsx
  src/History/NewKeyword.jsx
  src/shared/AddGroupButton.jsx
  src/shared/NewKeywordButton.jsx
Labels: feat, D+1

#23 feat: 드래그앤드롭 이후 DB와 동기화 시키는 기능 추가
  src/firebase/afterDragAndDrop.js
Labels: feat, D+1

#27 feat: mock data를 데이터베이스의 실제 데이터로 대체
  src/App.jsx
  src/History/ChangeGroupName.jsx
  src/History/DragAndDrop.jsx
  src/context/userIdContext.jsx
  src/firebase/CRUD.js
  src/firebase/getHistoryGroups.js
  src/firebase/user.js
  src/shared/Login.jsx
Labels: feat, D-0
